deployments:
  MoMa-Paintings:
    filename: ./docker-compose.yml
    vm_size: 1GB
    pipelines:
      dockerimage: ubuntu:bionic-20220427
      - api:
        scripts:
            - echo "API Tests are running..."
      - cart:
        scripts:
            - echo "Cart tests are running..."
      - frontend:
        scripts:
            - echo "Frontend tests are running..."
